### ISSUE TITLE
How to get more verbose debug output?

### ISSUE THREAD

**Issue by eabase** [measuresforjustice/textricator#17]
Is there a way to get more verbose debug output? 

This is not very helpful:
```bash
# ./textricator form --config=zzz4.yml --pages=3 --output-format=csv zzz_0.pdf zzz4.csv

Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<io.mfj.tex
tricator.form.config.Transition>` out of START_OBJECT token
 at [Source: (StringReader); line: 77, column: 9] (through reference chain: io.mfj.textricator.form.config.FormParseConfig["states"]->java.util.Linked
HashMap["winid"]->io.mfj.textricator.form.config.State["transitions"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1468)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1242)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1190)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:337)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:270)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:250)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:540)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:377)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3449)
        at io.mfj.textricator.form.config.FormParseConfigUtil.parseYaml(FormParseConfigUtil.kt:40)
        at io.mfj.textricator.form.config.FormParseConfigUtil.parseYaml(FormParseConfigUtil.kt:30)
        at io.mfj.textricator.cli.TextricatorCli.form(TextricatorCli.kt:170)
        at io.mfj.textricator.cli.TextricatorCli.main(TextricatorCli.kt:91)
```

**Comment by stephenbyrne-mfj** [comment]
Textricator relies on Jackson for YaML parsing, and those errors are all you can get from Textricator for malformed YaML files.
