### ISSUE TITLE
type and filter usage in Table type of processing is not working

### ISSUE THREAD

**Issue by eabase** [measuresforjustice/textricator#20]
type and filter usage in Table type of processing is not working

```
$ ./textricator.bat table --config=xxyt.yml xxy.pdf xxy.csv

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.parboiled.transform.AsmUtils (file:/F:/xxxx/lib/parboiled-java-1.3.1.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.parboiled.transform.AsmUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.IllegalArgumentException: both operands for > must be numbers or dates/times/datetimes

```

with

```yaml
extractor: "pdf.pdfbox"

top: 100
bottom: 630
right: 530

maxRowDistance: 2

# Define the columns, based on the x-coordinate where the column starts:
cols:
  "item": 73
  "date": 110
  "description": 193
  "quantity": 393
  "price": 459

types:
  "item":
    label: "Item"
  "date":
    label: "Date"
  "description":
    label: "Description"
  "quantity":
    label: "Qty"
  "price":
    label: "Price"

filter: 'item > 0'
```

Adding the `type: "integer"` gives an error:
```
$ ./textricator.bat table --config=xxyt.yml xxy.pdf xxy.csv
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant io.mfj.expr.ExDataType.INTEGER
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at io.mfj.expr.ExDataType.valueOf(ExDataType.kt)
        at io.mfj.textricator.record.RecordFilter.<init>(RecordFilter.kt:39)
        at io.mfj.textricator.Textricator.parseTable(Textricator.kt:269)
        at io.mfj.textricator.Textricator.parseTable(Textricator.kt:253)
        at io.mfj.textricator.Textricator.parseTable(Textricator.kt:242)
        at io.mfj.textricator.cli.TextricatorCli.table(TextricatorCli.kt:216)
        at io.mfj.textricator.cli.TextricatorCli.main(TextricatorCli.kt:90)
```

**Comment by eabase** [comment]
Adding the `type: "integer"` gives an error:
```
$ ./textricator.bat table --config=xxyt.yml xxy.pdf xxy.csv
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant io.mfj.expr.ExDataType.INTEGER
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at io.mfj.expr.ExDataType.valueOf(ExDataType.kt)
        at io.mfj.textricator.record.RecordFilter.<init>(RecordFilter.kt:39)
        at io.mfj.textricator.Textricator.parseTable(Textricator.kt:269)
        at io.mfj.textricator.Textricator.parseTable(Textricator.kt:253)
        at io.mfj.textricator.Textricator.parseTable(Textricator.kt:242)
        at io.mfj.textricator.cli.TextricatorCli.table(TextricatorCli.kt:216)
        at io.mfj.textricator.cli.TextricatorCli.main(TextricatorCli.kt:90)
```

**Comment by stephenbyrne-mfj** [comment]
The latest version of expr combined the `integer` and `double` types to just `number`. I updated the docs in ecb7111. Replace `integer` with `number` and it should just work.

**Comment by stephenbyrne-mfj** [comment]
Can you test this on the latest commit? Or provide the PDF?

**Comment by stephenbyrne-mfj** [comment]
Starting with https://github.com/measuresforjustice/expr/releases/tag/v5.0.25, `integer` and `double` were replaced with `number`.

**Comment by eabase** [comment]
>  Or provide the PDF?
I'm using the pdf in issue #19.

**Comment by stephenbyrne-mfj** [comment]
The problem here was the `integer` in the config. I think this issue can be closed.

**Comment by eabase** [comment]
@stephenbyrne-mfj 
I can't get `filter: 'item > 0'` to work, in the above. 
How many spaces are needed before using that?

**Comment by stephenbyrne-mfj** [comment]
Starting with the latest form config in #19, I modified it to filter on quantity > 0 by adding
`type: number` to `/valueTypes/quantity` and `filter: 'quantity > 0' to `/recordTypes/item`:

```yml
extractor: "pdf.pdfbox"

header:
  default: 100
footer:
  default: 600

maxRowDistance: 2

rootRecordType: item
recordTypes:
  item:
    label: "item"
    valueTypes:
      - item
      - date
      - description
      - order_number
      - quantity
      - price
    filter: 'quantity > 0'

valueTypes:
  item:
    label: "Item"
  date:
    label: "Date"
  description:
    label: "Description"
  order_number:
    label: "OrderNo"
  quantity:
    label: "Qty"
    type: number
  price:
    label: "Price"

initialState: "INIT"

states:
  INIT:
    include: false
    transitions:
      -
        condition: item
        nextState: item
      # stay in INIT until first item is reached 
      - condition: any
        nextState: INIT

  item:
    startRecord: true
    transitions:
      -
        condition: date
        nextState: date  

  date:
    include: true
    transitions:
      -
        condition: description
        nextState: description  

  description:
    include: true
    transitions:
      -
        condition: description
        nextState: description     
      -
        condition: order_number_title
        nextState: order_number_title
      -
        condition: quantity
        nextState: quantity
      -
        condition: item
        nextState: item

  order_number_title:
    include: false
    transitions:
      -
        condition: order_number
        nextState: order_number

  order_number:
    include: true
    transitions:
      -
        condition: order_number
        nextState: order_number
      -
        condition: quantity
        nextState: quantity
      -
        condition: item
        nextState: item

  quantity:
    include: true
    transitions:
      - 
        condition: price
        nextState: price

  price:
    include: true
    transitions:
      -
        condition: end
        nextState: end
      - 
        condition: order_number_title
        nextState: order_number_title
      -
        condition: item
        nextState: item

  end:
    include: false
    transitions:
      -
        condition: any
        nextState: end

conditions:

  item:         '73 < ulx < 110 and text =~ /(\\d)*/'
  date:         '110 < ulx < 181 and text =~ /([0-9\\-]*)/'
  description:  '193 < ulx < 366'
  order_number: '245 <= ulx <= 300 and text =~ /^([0-9]{6})-([0-9]{2})/'
  order_number_title: 'text = "OrderNo:" and 195 <= ulx <= 220'
  quantity:     '393 < ulx < 459'
  price:        '459 < ulx < 523'

  end:          'text =~ /(Footer)/'
  any: "1 = 1"
```

I think the problem using the table based config is that in some rows it is blank.

**Comment by stephenbyrne-mfj** [comment]
Oh, I see the problem. It is trying to convert the word "Item" from the PDF's header row. Adjusting `top` down farther to omit that row prevents that from happening, but it still fails when it gets to the row between items 1 and 2 because item is blank.

**Comment by stephenbyrne-mfj** [comment]
Expr will need a way to test for null.

**Comment by stephenbyrne-mfj** [comment]
Expr has a way to test for null, it just wasn't documented.

```yml
extractor: "pdf.pdfbox"

top: 120
bottom: 630
right: 530

maxRowDistance: 2

# Define the columns, based on the x-coordinate where the column starts:
cols:
  "item": 73
  "date": 110
  "description": 193
  "quantity": 393
  "price": 459

types:
  "item":
    label: "Item"
    type: number
  "date":
    label: "Date"
  "description":
    label: "Description"
  "quantity":
    label: "Qty"
    type: "number"
  "price":
    label: "Price"

filter: 'item != null'
```

**Comment by stephenbyrne-mfj** [comment]
https://github.com/measuresforjustice/expr/commit/dcdd5b31e454e9dad3ec844eb1efa75bff632021

**Comment by eabase** [comment]
I just tried that config above and it only give me one row...

**Comment by stephenbyrne-mfj** [comment]
I just used that config using textricator 9.4.64 (released today), and I got:

```csv
page,Item,Date,Description,Qty,Price
1,1,2021-04-24,El-Gato Stream,1,1000.00
1,2,2021-04-23,Something,2,200.00
1,3,2021-04-22,Something Else,3,300.00
1,4,2021-04-21,Something 2,4,400.00
1,5,2021-04-21,Someone Three,0,500.00
```

**Comment by eabase** [comment]
My bad. I apologize, sleepy eyes missed the change of `>0` to `!= null`.
