### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: first.font.name must not be null

### ISSUE THREAD

**Issue by eabase** [measuresforjustice/textricator#21]
I'm getting these every now and then, and I don't see any issue with the PDF file. 

```
Apr 29, 2021 9:19:24 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for 113 (113) in font null

Exception in thread "main" java.lang.NullPointerException: first.font.name must not be null
        at io.mfj.textricator.extractor.pdfbox.TextBoxPdfTextStripper.addWord(TextBoxPdfTextStripper.kt:119)
        at io.mfj.textricator.extractor.pdfbox.TextBoxPdfTextStripper.writeString(TextBoxPdfTextStripper.kt:73)
        at org.apache.pdfbox.text.PDFTextStripper.writeLine(PDFTextStripper.java:1737)
        at org.apache.pdfbox.text.PDFTextStripper.writePage(PDFTextStripper.java:669)
        at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:398)
        at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:325)
        at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:272)
        at org.apache.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:233)
        at io.mfj.textricator.extractor.pdfbox.PdfboxTextExtractor.extract(PdfboxTextExtractor.kt:36)
        at io.mfj.textricator.Textricator$extractPages$2.invoke(Textricator.kt:318)
        at io.mfj.textricator.Textricator$extractPages$2.invoke(Textricator.kt:46)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:311)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
        at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:169)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at io.mfj.textricator.record.output.CsvRecordOutput.write(CsvRecordOutput.kt:146)
        at io.mfj.textricator.Textricator.parseTable(Textricator.kt:255)
        at io.mfj.textricator.Textricator.parseTable(Textricator.kt:242)
        at io.mfj.textricator.cli.TextricatorCli.table(TextricatorCli.kt:216)
        at io.mfj.textricator.cli.TextricatorCli.main(TextricatorCli.kt:90)
```

**Comment by stephenbyrne-mfj** [comment]
Can you share the PDF that you get this error with?

**Comment by eabase** [comment]
Oh my bad... I don't recall anymore what files or even the command. 
So yeah, close this.
