### ISSUE TITLE
Cannot Run School Example

### ISSUE THREAD

**Issue by jg43b** [measuresforjustice/textricator#8]
The following command, taken from the readme, produces an error:

```
./textricator text --input-format=pdf.pdfbox school-employee-list.pdf
```

The error is as follows:

```
Exception in thread "main" java.io.IOException: Error: End-of-File, expected line
	at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1119)
	at org.apache.pdfbox.pdfparser.COSParser.parseHeader(COSParser.java:2574)
	at org.apache.pdfbox.pdfparser.COSParser.parsePDFHeader(COSParser.java:2553)
	at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:213)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1160)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1057)
	at io.mfj.textricator.extractor.pdfbox.PdfboxTextExtractor.<init>(PdfboxTextExtractor.kt:28)
	at io.mfj.textricator.extractor.pdfbox.PdfboxTextExtractorFactory.create(PdfboxTextExtractorFactory.kt:27)
	at io.mfj.textricator.Textricator.getExtractor(Textricator.kt:274)
	at io.mfj.textricator.Textricator.parseForm(Textricator.kt:135)
	at io.mfj.textricator.Textricator.parseForm$default(Textricator.kt:132)
	at io.mfj.textricator.cli.TextricatorCli.form(TextricatorCli.kt:178)
	at io.mfj.textricator.cli.TextricatorCli.main(TextricatorCli.kt:91)
```

I was able to run it on a different machine with `OpenJDK 12.0.1`, but the machine where I'm getting the error has `java 10.0.2`.

**Comment by stephenbyrne-mfj** [comment]
Java 10 is dead. It should work on all currently supported versions (8,11,13).

**Comment by thavidu** [comment]
For anyone stumbling upon this from google: you may also get the same error if you right-clicked and save-link-as on the school pdf from the quickstart in the readme :) Don't waste your time thinking the java version is wrong- that link takes you to a html page and you have to hit 'download' from there, so what you saved as a pdf was actually the webpage by accident 😅 make sure the file you are trying to extract opens in your favourite pdf reader before running textricator on it.
